version: '3.8'

services:
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

networks:
  nesjs-network:
